apps/neoscan_web/lib/neoscan_web/router.ex
defmodule NeoscanWeb.Router do
  use NeoscanWeb, :router
  alias NeoscanWeb.Plugs.Locale
  alias NeoscanWeb.Plugs.Tooltip

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(Locale)
    plug(Tooltip)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/wobserver", Wobserver.Web.Router)

  scope "/", NeoscanWeb do
    pipe_through(:browser)

    get("/", HomeController, :index)
    post("/", HomeController, :search)

    get("/address/:address", AddressController, :index)
    get("/address/:address/:page", AddressController, :page)

    get("/addresses/:page", AddressesController, :page)

    get("/block/:block_hash", BlockController, :index)
    get("/block/:block_hash/:page", BlockController, :page)

    get("/blocks/:page", BlocksController, :page)

    get("/docs", DocsController, :index)

    get("/price/:from/:to/:graph", PriceController, :index)

    get("/transaction/:transaction_hash", TransactionController, :index)

    get("/transactions/:page", TransactionsController, :page)

    get("/asset/:asset_hash", AssetController, :index)

    get("/assets/:page", AssetsController, :page)
  end

  scope "/api/main_net/v1", NeoscanWeb do
    pipe_through(:api)

    # used by neon-js / wallet
    get("/get_balance/:address", ApiController, :get_balance)
    get("/get_unclaimed/:address", ApiController, :get_unclaimed)
    get("/get_claimable/:address", ApiController, :get_claimable)
    get("/get_all_nodes", ApiController, :get_all_nodes)

    get(
      "/get_last_transactions_by_address/:address",
      ApiController,
      :get_last_transactions_by_address
    )

    get(
      "/get_last_transactions_by_address/:address/:page",
      ApiController,
      :get_last_transactions_by_address
    )

    get("/get_height", ApiController, :get_height)

    # Used by NEX
    get("/get_address_abstracts/:address/:page", ApiController, :get_address_abstracts)

    get(
      "/get_address_to_address_abstracts/:address1/:address2/:page",
      ApiController,
      :get_address_to_address_abstracts
    )

    # for future use
    get("/get_claimed/:address", ApiController, :get_claimed)
    get("/get_block/:block_hash", ApiController, :get_block)
    get("/get_transaction/:transaction_hash", ApiController, :get_transaction)
  end

  scope "/graphql" do
    pipe_through(:api)

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: NeoscanWeb.Schema,
      interface: :simple
    )

    forward("/", Absinthe.Plug, schema: NeoscanWeb.Schema)
  end

  # Other scopes may use custom stacks.
  # scope "/api", NeoscanWeb do
  #   pipe_through :api
  # end
end

apps/neoscan_web/lib/neoscan_web/controllers/block_controller.ex
defmodule NeoscanWeb.BlockController do
  use NeoscanWeb, :controller

  alias Neoscan.Blocks
  alias Neoscan.Transactions
  alias NeoscanWeb.Helper

  @block_hash_page_spec [
    block_hash: %{
      type: :integer_or_base16
    },
    page: %{
      type: :integer,
      default: 1
    }
  ]

  def index(conn, parameters) do
    page(conn, parameters)
  end

  def page(conn, params) do
    if_valid_query conn, params, @block_hash_page_spec do
      block = Blocks.get(parsed.block_hash)

      if is_nil(block) do
        redirect(conn, to: home_path(conn, :index))
      else
        transactions = Transactions.get_for_block(block.index, parsed.page)
        transactions = Helper.render_transactions(transactions)
        render(conn, "block.html", block: block, transactions: transactions, page: parsed.page)
      end
    end
  end
end

apps/neoscan_web/lib/neoscan_web/controllers/blocks_controller.ex
defmodule NeoscanWeb.BlocksController do
  use NeoscanWeb, :controller

  alias Neoscan.Blocks

  @page_spec [
    page: %{
      type: :integer,
      default: 1
    }
  ]

  def page(conn, params) do
    if_valid_query conn, params, @page_spec do
      blocks = Blocks.paginate(parsed.page)
      render(conn, "blocks.html", blocks: blocks, page: parsed.page, total: blocks.total_entries)
    end
  end
end

apps/neoscan_web/lib/neoscan_web/views/block_view.ex
defmodule NeoscanWeb.BlockView do
  use NeoscanWeb, :view
  import Number.Delimit
  import NeoscanWeb.CommonView
end

apps/neoscan_web/lib/neoscan_web/views/blocks_view.ex
defmodule NeoscanWeb.BlocksView do
  use NeoscanWeb, :view
  import Number.Delimit
  import NeoscanWeb.CommonView
end

apps/neoscan_web/lib/neoscan_web/templates/blocks/blocks.html.eex
<h1 class="content-title"><%= gettext "Blocks"%></h1>

<!-- All blocks content -->
<section id="all-blocks-wrapper">

  <div class="detail-bar">
    <p class="detail-type detail-type-first-4-col"><%= gettext "Height" %></p>
    <p class="detail-type col-2-width"><%= gettext "Size" %></p>
    <p class="detail-type col-2-width"><%= gettext "Transactions" %></p>
    <p class="detail-type col-3-width"><%= gettext "Created on" %></p>
    <p class="detail-type col-1-width"><%= gettext "Block Time" %></p>
    <p class="detail-type tablet-full-width"><%= gettext "All block information"%></p>
  </div>

  <!-- Blocks -->
  <section id="blocks-wrapper">

    <div class="blocks-list">

      <%= for block <- @blocks do %>
        <!-- Block -->
        <div class="full-width-bar block-number">
          <div class="information-wrapper">
            <p class="fa fa-signal medium-detail-text"></p>
            <a href="<%= block_path( @conn, :index, render_hash(block.hash)) %>" alt="<%= gettext "View block"%>" title="<%= gettext "View block"%>" class="large-blue-link col-4-width">
              <span class="tablet-detail-text"><%= gettext "Block"%>: </span>
              <%=number_to_delimited(block.index)%>
            </a>
            <div class="secondary-info-wrapper">
              <p class="medium-detail-text col-2-width">
                <span class="tablet-detail-text"><%= gettext "Size"%>: </span>
                <%= number_to_delimited(block.size) %> <%= gettext "bytes" %>
              </p>
              <p class="medium-detail-text col-2-width">
                <span class="tablet-detail-text"><%= gettext "Transactions"%>: </span>
                <%= number_to_delimited(block.tx_count) %>
              </p>
              <p class="medium-detail-text col-3-width">
                <span class="tablet-detail-text"><%= gettext "Created"%>: </span>
                <span class="utc_time"><%= render_date_time(block.time) %></span>
              </p>
              <p class="medium-detail-text col-1-width">
                <span class="tablet-detail-text"><%= gettext "Block Time"%>: </span>
                <%= number_to_delimited(block.lag) %> seconds
              </p>
            </div>
          </div>
        </div>
      <%end%>

    </div>

  </section>

  <p  class="number-counter"><%= gettext "Blocks"%> <%= get_current_min_qtd(@page, @total) %> <%= gettext "to"%> <%= get_current_max_qtd(@page, @total) %> <%= gettext "of"%> <%= number_to_delimited(@total) %></p>
  <div class="see-all-button-container">
    <div class="btn-group">
      <%= if @page != 1 do %>
        <a href="<%= blocks_path(@conn, :page, to_string(@page - 1)) %>" class="button btn btn-primary"><i class="fa fa-angle-left"></i></a>
      <% end %>
      <%= if check_last(@page, @total) do %>
      <a href="<%= blocks_path(@conn, :page, to_string(@page + 1)) %>" class="button btn btn-primary"><i class="fa fa-angle-right"></i></a>
      <% end %>
    </div>
  </div>
</section>