apps/neoscan_web/lib/neoscan_web/router.ex
defmodule NeoscanWeb.Router do
  use NeoscanWeb, :router
  alias NeoscanWeb.Plugs.Locale
  alias NeoscanWeb.Plugs.Tooltip

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(Locale)
    plug(Tooltip)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/wobserver", Wobserver.Web.Router)

  scope "/", NeoscanWeb do
    pipe_through(:browser)

    get("/", HomeController, :index)
    post("/", HomeController, :search)

    get("/address/:address", AddressController, :index)
    get("/address/:address/:page", AddressController, :page)

    get("/addresses/:page", AddressesController, :page)

    get("/block/:block_hash", BlockController, :index)
    get("/block/:block_hash/:page", BlockController, :page)

    get("/blocks/:page", BlocksController, :page)

    get("/docs", DocsController, :index)

    get("/price/:from/:to/:graph", PriceController, :index)

    get("/transaction/:transaction_hash", TransactionController, :index)

    get("/transactions/:page", TransactionsController, :page)

    get("/asset/:asset_hash", AssetController, :index)

    get("/assets/:page", AssetsController, :page)
  end

  scope "/api/main_net/v1", NeoscanWeb do
    pipe_through(:api)

    # used by neon-js / wallet
    get("/get_balance/:address", ApiController, :get_balance)
    get("/get_unclaimed/:address", ApiController, :get_unclaimed)
    get("/get_claimable/:address", ApiController, :get_claimable)
    get("/get_all_nodes", ApiController, :get_all_nodes)

    get(
      "/get_last_transactions_by_address/:address",
      ApiController,
      :get_last_transactions_by_address
    )

    get(
      "/get_last_transactions_by_address/:address/:page",
      ApiController,
      :get_last_transactions_by_address
    )

    get("/get_height", ApiController, :get_height)

    # Used by NEX
    get("/get_address_abstracts/:address/:page", ApiController, :get_address_abstracts)

    get(
      "/get_address_to_address_abstracts/:address1/:address2/:page",
      ApiController,
      :get_address_to_address_abstracts
    )

    # for future use
    get("/get_claimed/:address", ApiController, :get_claimed)
    get("/get_block/:block_hash", ApiController, :get_block)
    get("/get_transaction/:transaction_hash", ApiController, :get_transaction)
  end

  scope "/graphql" do
    pipe_through(:api)

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: NeoscanWeb.Schema,
      interface: :simple
    )

    forward("/", Absinthe.Plug, schema: NeoscanWeb.Schema)
  end

  # Other scopes may use custom stacks.
  # scope "/api", NeoscanWeb do
  #   pipe_through :api
  # end
end

apps/neoscan_web/lib/neoscan_web/views/layout_view.ex
defmodule NeoscanWeb.LayoutView do
  use NeoscanWeb, :view
  alias Phoenix.Controller
  alias Plug.Conn
  alias NeoscanWeb.ViewHelper

  @languages %{
    "en" => "English",
    "es" => "Español",
    "nl" => "Nederlands",
    "fr" => "Français",
    "pt-br" => "Português",
    "it" => "Italiano",
    "de" => "Deutsch",
    "ru" => "Русский",
    "ro" => "Română"
  }

  def is_home_path(conn) do
    Controller.controller_module(conn) == NeoscanWeb.HomeController
  end

  def is_blocks_path(conn) do
    Controller.controller_module(conn) == NeoscanWeb.BlocksController
  end

  def is_transactions_path(conn) do
    Controller.controller_module(conn) == NeoscanWeb.TransactionsController
  end

  def is_addresses_path(conn) do
    Controller.controller_module(conn) == NeoscanWeb.AddressesController
  end

  def is_assets_path(conn) do
    Controller.controller_module(conn) == NeoscanWeb.AssetsController
  end

  def get_page(conn) do
    Controller.controller_module(conn)
    |> to_string
    |> String.replace("Elixir.NeoscanWeb.", "")
    |> String.replace("Controller", "")
  end

  def get_language(conn) do
    Conn.get_session(conn, "locale")
  end

  def get_lang_text(conn) do
    case @languages[get_language(conn)] do
      nil -> "English"
      lang -> lang
    end
  end

  def get_tooltips(conn) do
    ViewHelper.get_tooltips(conn)
  end
end

apps/neoscan_web/lib/neoscan_web/templates/layout/app.html.eex
<!DOCTYPE>

<html lang="en">
<head>
<meta charset="utf-8">
	<title>NEOSCAN | <%= get_page(@conn) %></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone=no"/>
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<link rel="shortcut icon" href="<%= static_path(@conn, "/favicon.ico") %>">

	<!-- CSS import + FontAwesome import -->
	<link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">

	<!-- Open graph protocol data -->
	<meta property="og:title" content="NeoScan - NEO Blockchain Explorer" />
	<meta property="og:url" content="[neoscan.io]" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="A blockchain explorer for the NEO project. Track blocks, addresses, balances, transactions, NEO, GAS and other assets on the platform." />
	<meta property="og:image" content="<%= static_path(@conn, "/images/coz.png") %>" />
		
	<!-- Twitter card data -->
	<meta name="twitter:title" content="NeoScan - NEO Blockchain Explorer"/>
	<meta name="twitter:url" content="[neoscan.io]">
	<meta name="twitter:description" content="A blockchain explorer for the NEO project. Track blocks, addresses, balances, transactions, NEO, GAS and other assets on the platform." />
	<meta name="twitter:card" content="summary"/>
	<meta name="twitter:image" content="<%= static_path(@conn, "/images/coz.png") %>"/>

	<!-- Font imports: Orbitron, Source Sans Pro, Teko -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i,700,700i|Teko:300,500" rel="stylesheet">

</head>

<body>

	<div id="main-wrapper">

		<!-- Navigation -->
		<nav id="navigation">

			<button class="hamburger hamburger--spin" type="button">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
					</span>
			</button>

			<!-- Language selector dropdown -->
			<div class="lang-dropdown-wrapper">
        <div id="language-dropdown">
          <div class="selected-language-text"><%= get_lang_text(@conn) %></div>
        </div>
				<ul class="language-dropdown-options">
          <li value="en" class="<%= if get_language(@conn) == "en" do %>active-lang<% end %>">English</li>

	  <li value="es" class="<%= if get_language(@conn) == "es" do %>active-lang<% end %>">Español</li>
          <li value="nl" class="<%= if get_language(@conn) == "nl" do %>active-lang<% end %>">Nederlands</li>
          <li value="de" class="<%= if get_language(@conn) == "de" do %>active-lang<% end %>">Deutsch</li>
          <li value="fr" class="<%= if get_language(@conn) == "fr" do %>active-lang<% end %>">Français</li>
          <li value="it" class="<%= if get_language(@conn) == "it" do %>active-lang<% end %>">Italiano</li>
          <li value="pt_BR" class="<%= if get_language(@conn) == "pt_BR" do %>active-lang<% end %>">Português</li>
          <li value="ro" class="<%= if get_language(@conn) == "ro" do %>active-lang<% end %>">Română</li>
          <li value="ru" class="<%= if get_language(@conn) == "ru" do %>active-lang<% end %>">Русский</li>
          <li value="zh" class="<%= if get_language(@conn) == "zh" do %>active-lang<% end %>">中文</li>
          <li value="ja" class="<%= if get_language(@conn) == "ja" do %>active-lang<% end %>">日本語</li>
				</ul>
			</div>

			<!-- Logo -->
			<div class="logo-wrapper">
        <a href="/" alt="NEOSCAN Home">
          <img src="<%= static_path(@conn, "/images/NEOSCAN_Logo.svg") %>" alt="<%= gettext "NEOSCAN Home" %>" title="<%= gettext "NEOSCAN Home" %>" width="163px" height="32px" class="neoscan-logo" />
        </a>
			</div>

			<!-- Search -->
      <%= form_for @conn, home_path(@conn, :index), [as: :search], fn f -> %>
        <%= text_input f, :for,placeholder: gettext("Block Height, Hash, Address or Transaction id"),class: "searchbar fa fa-search", type: "search" %>
				<%= submit "", [class: "icon search-btn fa fa-search"]  %>
        <%= error_tag f, :for %>
      <% end %>

			<!-- Navigation links -->
			<div class="nav-wrapper">
				<ul class="nav-links-list">
					<li class="remove-margin-left">
						<a href="<%= home_path(@conn, :index) %>" alt="Explorer" title="Explorer" class="nav-link <%= if is_home_path(@conn), do: " active" %>"><%= gettext "Explorer" %></a>
					</li>
					<li>
						<a href="<%= transactions_path(@conn, :page, "1") %>" alt="Explorer" title="Explorer" class="nav-link <%= if is_transactions_path(@conn), do: " active" %>"><%= gettext "Transactions" %></a>
					</li>
					<li>
						<a href="<%= addresses_path(@conn, :page, "1") %>" alt="Explorer" title="Explorer" class="nav-link <%= if is_addresses_path(@conn), do: " active" %>"><%= gettext "Wallet Addresses" %></a>
					</li>
					<li>
						<a href="<%= blocks_path(@conn, :page, "1") %>" alt="Explorer" title="Explorer" class="nav-link <%= if is_blocks_path(@conn), do: " active" %>"><%= gettext "Blocks" %></a>
					</li>
					<li>
						<a href="<%= assets_path(@conn, :page, "1") %>" alt="Explorer" title="Explorer" class="nav-link <%= if is_assets_path(@conn), do: " active" %>"><%= gettext "Assets" %></a>
					</li>
					<li>
						<a href="<%= docs_path(@conn, :index) %>" alt="Explorer" title="Explorer" class="nav-link"><%= gettext "API" %></a>
					</li>
				</ul>
			</div>
		</nav>



		<!-- Main content area -->
		<section id="main-content-wrapper">
      <%= render @view_module, @view_template, assigns %>
    </section>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <!-- Footer -->
		<footer id="footer">
			<div class="footer-content-wrapper">
				<div class="left-footer-information">
					<img src="<%= static_path(@conn, "/images/NEOSCAN_Logo.svg") %>" alt="NEOSCAN Home" title="NEOSCAN Home" class="neoscan-logo-footer" width="136px" height="27px" />
					<p class="medium-detail-text"><%= gettext "The source code is" %> <a href="http://opensource.org/licenses/mit-license.php" alt="<%= gettext "View MIT License"%>" title="<%= gettext "View MIT License"%>" class="large-blue-link"><%= gettext "licensed" %> MIT</a></li>
					<p class="medium-detail-text"><%= gettext "The website content is licensed" %> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" alt="CC ANS 4.0" title="CC ANS 4.0" class="large-blue-link">CC ANS 4.0</a></p>
					<p class="medium-detail-text"><a href="https://neoscan-testnet.io/" alt="<%= gettext "NEOSCAN Testnet"%>" title="<%= gettext "NEOSCAN Testnet"%>" class="large-blue-link"><%= gettext "NEOSCAN Testnet" %></a></p>
					<p class="medium-detail-text">&copy; 2018 <a href="http://cityofzion.io/" alt="<%= gettext "Visit City of Zion"%>" title="<%= gettext "Visit City of Zion"%>" class="large-blue-link"><%= gettext "City Of Zion" %></a></p>
				</div>

				<div class="right-footer-information">
					<div class="footer-link-wrapper">
						<a href="https://discord.gg/Md676aR" alt="<%= gettext "NEO Discord"%>" title="<%= gettext "NEO Discord"%>" class="coz-discord"><%= gettext "NEO Discord" %></a>
					</div>
					<div class="footer-link-wrapper">
						<a href="https://github.com/CityOfZion" alt="<%= gettext "City of Zion Github" %>" title="<%= gettext "City of Zion Github" %>" class="coz-github"><%= gettext "City of Zion Github" %></a>
					</div>
					<div class="footer-link-wrapper">
						<a href="<%= docs_path(@conn, :index) %>" alt="<%= gettext "NEOSCAN API" %>" title="<%= gettext "NEOSCAN API" %>" class="coz-api"><%= gettext "NEOSCAN API" %></a>
					</div>
          <div class="footer-link-wrapper">
            <div class="btn btn-primary tooltip-btn">
              <%= if get_tooltips(@conn) == "on" do %><%= gettext "Tooltips On " %><i class="fa fa-eye tooltip-eye" aria-hidden="true"></i><% end %>
              <%= if get_tooltips(@conn) == "off" do %><%= gettext "Tooltips Off " %><i class="fa fa-eye-slash tooltip-eye" aria-hidden="true"></i><% end %>
            </div>
          </div>
				</div>
			</div>
		</footer>

	</div>


</body>
</html>