apps/neoscan_web/lib/neoscan_web/router.ex
defmodule NeoscanWeb.Router do
  use NeoscanWeb, :router
  alias NeoscanWeb.Plugs.Locale
  alias NeoscanWeb.Plugs.Tooltip

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(Locale)
    plug(Tooltip)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/wobserver", Wobserver.Web.Router)

  scope "/", NeoscanWeb do
    pipe_through(:browser)

    get("/", HomeController, :index)
    post("/", HomeController, :search)

    get("/address/:address", AddressController, :index)
    get("/address/:address/:page", AddressController, :page)

    get("/addresses/:page", AddressesController, :page)

    get("/block/:block_hash", BlockController, :index)
    get("/block/:block_hash/:page", BlockController, :page)

    get("/blocks/:page", BlocksController, :page)

    get("/docs", DocsController, :index)

    get("/price/:from/:to/:graph", PriceController, :index)

    get("/transaction/:transaction_hash", TransactionController, :index)

    get("/transactions/:page", TransactionsController, :page)

    get("/asset/:asset_hash", AssetController, :index)

    get("/assets/:page", AssetsController, :page)
  end

  scope "/api/main_net/v1", NeoscanWeb do
    pipe_through(:api)

    # used by neon-js / wallet
    get("/get_balance/:address", ApiController, :get_balance)
    get("/get_unclaimed/:address", ApiController, :get_unclaimed)
    get("/get_claimable/:address", ApiController, :get_claimable)
    get("/get_all_nodes", ApiController, :get_all_nodes)

    get(
      "/get_last_transactions_by_address/:address",
      ApiController,
      :get_last_transactions_by_address
    )

    get(
      "/get_last_transactions_by_address/:address/:page",
      ApiController,
      :get_last_transactions_by_address
    )

    get("/get_height", ApiController, :get_height)

    # Used by NEX
    get("/get_address_abstracts/:address/:page", ApiController, :get_address_abstracts)

    get(
      "/get_address_to_address_abstracts/:address1/:address2/:page",
      ApiController,
      :get_address_to_address_abstracts
    )

    # for future use
    get("/get_claimed/:address", ApiController, :get_claimed)
    get("/get_block/:block_hash", ApiController, :get_block)
    get("/get_transaction/:transaction_hash", ApiController, :get_transaction)
  end

  scope "/graphql" do
    pipe_through(:api)

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: NeoscanWeb.Schema,
      interface: :simple
    )

    forward("/", Absinthe.Plug, schema: NeoscanWeb.Schema)
  end

  # Other scopes may use custom stacks.
  # scope "/api", NeoscanWeb do
  #   pipe_through :api
  # end
end

apps/neoscan_web/lib/neoscan_web/views/shared_view.ex
defmodule NeoscanWeb.SharedView do
  use NeoscanWeb, :view
  import NeoscanWeb.CommonView
end

apps/neoscan_web/lib/neoscan_web/templates/shared/transaction_panel.html.eex
<div class="transaction-panel">
    <%= unless Enum.empty?(@transaction.sent_from ++ @transaction.claimed ++ @transaction.sent_to ++ @transaction.registered ++ @transaction.minted) do %>
    <div class="sent-from-wrapper">
      <%= unless Enum.empty?(@transaction.sent_from) do %>
        <p class="large-detail-text"><%= gettext "Sent from" %></p>
        <%= render NeoscanWeb.SharedView, "transaction_panel_entries.html", conn: @conn, entries:  @transaction.sent_from %>
      <% end %>
      <%= unless Enum.empty?(@transaction.claimed) do %>
        <p class="large-detail-text"><%= gettext "Claimed from" %></p>
        <%= render NeoscanWeb.SharedView, "transaction_panel_entries.html", conn: @conn, entries:  @transaction.claimed %>
      <% end %>
      <%= unless Enum.empty?(@transaction.minted) do %>
        <p class="large-detail-text"><%= gettext "Minted" %></p>
        <%= render NeoscanWeb.SharedView, "transaction_panel_entries.html", conn: @conn, entries:  @transaction.minted %>
      <% end %>
    </div>
    <img src="<%= static_path(@conn, "/images/ICON_Sent-arrow.svg")%>" alt="Sent arrow" title="Sent arrow" class="transaction-sent-arrow" />
    <div class="sent-to-wrapper">
      <%= unless Enum.empty?(@transaction.sent_to) do %>
        <p class="large-detail-text"><%= gettext "Sent to" %></p>
        <%= render NeoscanWeb.SharedView, "transaction_panel_entries.html", conn: @conn, entries:  @transaction.sent_to %>
      <% end %>
      <%= unless Enum.empty?(@transaction.registered) do %>
          <p class="large-detail-text"><%= gettext "Registered" %></p>
        <%= render NeoscanWeb.SharedView, "transaction_panel_entries.html", conn: @conn, entries:  @transaction.registered %>
        <% end %>
    </div>
    <% end %>
    <%= if @show_info do %>
    <div class="other-transaction-information">
      <p>Network fee: <%=@transaction.net_fee%> <%= gettext "GAS" %> &middot; <%= gettext "System Fee" %>: <%=@transaction.sys_fee%> <%= gettext "GAS" %> &middot; <%= gettext "Data Size" %>: <%=@transaction.size%> bytes</p>
    </div>
    <% end %>
  </div>

apps/neoscan_web/lib/neoscan_web/templates/shared/transaction_panel_entries.html.eex
<%= for entry <- @entries do %>
  <div class="individual-transaction">
    <%= unless entry.address_hash == <<0>> do %>
    <a href='<%= address_path(@conn, :index, render_address_hash(entry.address_hash))%>' alt="View wallet address" title="View wallet address" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= render_address_hash(entry.address_hash) %></a>
    <% end %>
    <p class="neo-amount large-blue-link"><span class="fa <%= render_asset_style(entry.asset.type) %>"></span><%= render_balance(entry) %> <%= entry.asset.symbol || entry.asset.name %></p>
  </div>
<% end %>

apps/neoscan_web/lib/neoscan_web/templates/shared/transactions_wrapper.html.eex
  <div class="detail-bar">
    <p class="detail-type detail-type-first-2-col"><%= gettext "Type" %></p>
    <p class="detail-type col-6-width"><%= gettext "Transaction ID" %></p>
    <p class="detail-type col-2-width"><%= gettext "Completed on" %></p>
    <p class="detail-type tablet-full-width"><%= gettext "All transaction information" %></p>
  </div>
<section id="transactions-wrapper">
    <div class="transactions-list">
      <%= for transaction <- @transactions do %>
        <div class="full-width-bar <%= get_class(transaction.type)%>">
          <div class="information-wrapper">
            <p class="medium-detail-text col-2-width"><span class="fa <%= get_transaction_style(transaction.type) %>"></span><%= Gettext.gettext(NeoscanWeb.Gettext, get_transaction_name(transaction.type)) %></p>
            <div class="secondary-info-wrapper">
              <a href="<%=transaction_path(@conn, :index, render_hash(transaction.hash) )%>" alt="<%= gettext "View transaction"%>" title="<%= gettext "View transaction" %>" class="large-blue-link col-6-width"><%= render_hash(transaction.hash) %>&#8230;</a>
              <p class="medium-detail-text col-2-width remove-550px">
                <span class="utc_time"><%= render_date_time(transaction.block_time) %></span>
              </p>
            </div>
          </div>
          <button class="btn-accordion"><img src="<%= static_path(@conn, "/images/ICON_DownArrow.svg") %>" alt="Accordion down arrow" title="Accordion down arrow" class="accordion-down-arrow" width="13px" height="8px" /></button>
          <%= render NeoscanWeb.SharedView, "transaction_panel.html", conn: @conn, transaction: transaction, show_info: true %>
        </div>
      <%end%>
    </div>
</section>